# Generated by Django 5.2.5 on 2026-01-27 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('datos', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Equipo')),
                ('modelo', models.CharField(max_length=50, unique=True, verbose_name='Código del Equipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Equipo')),
                ('sistema', models.CharField(choices=[('VRF', 'VRF'), ('Compacto', 'Compacto'), ('Chiller', 'Chiller'), ('fancoil', 'Fan Coil'), ('UMA', 'Unidad Manejadora de Aire')], default='VRF', max_length=10, verbose_name='Tipo de Sistema')),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad del Equipo (TR)')),
                ('mca', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='mca (A)')),
                ('mfa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='mcc (A)')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Material')),
                ('familia', models.CharField(max_length=100, verbose_name='Familia del Material')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Material')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('sistema', models.CharField(choices=[('VRF', 'VRF'), ('CHW', 'Agua Helada (Chilled Water)')], default='VRF', max_length=3, verbose_name='Tipo de Sistema')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo Unitario')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('especialidad', models.CharField(choices=[('Instalación VRF', 'Instalación VRF'), ('Instalación CHW', 'Instalación CHW'), ('Mantenimiento', 'Mantenimiento'), ('Ductería P3', 'Ductería P3'), ('Ductería Galvanizada', 'Ductería Galvanizada'), ('Obra Civil', 'Obra Civil'), ('Eléctricidad', 'Electricidad'), ('Izaje', 'Izaje')], max_length=50, verbose_name='Especialidad')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Alternativo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Cotización')),
                ('datos', models.JSONField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corrida', verbose_name='Corrida Origen')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Obra')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección de la Obra')),
                ('toneladas_frio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Toneladas de Frío')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha Fin Estimada')),
                ('presupuesto_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Presupuesto Inicial')),
                ('ingeniero_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_ingeniero', to=settings.AUTH_USER_MODEL, verbose_name='Ingeniero Encargado')),
                ('centro_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_centro_servicio', to='app.personal', verbose_name='Centro de Servicio (Personal Técnico)')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Fase')),
                ('presupuesto_asignado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Presupuesto Asignado')),
                ('costo_mano_de_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Mano de Obra (Fase)')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.obra', verbose_name='Obra')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaEquipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiales_requeridos', models.JSONField(help_text="Lista de dicts: [{'codigo': 'MAT001', 'cantidad': 5}, ...]", verbose_name='Materiales Requeridos')),
                ('equipo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_materiales', to='app.equipo', to_field='modelo', verbose_name='Equipo de Origen')),
            ],
            options={
                'verbose_name': 'Regla Equipo a Material',
                'verbose_name_plural': 'Reglas Equipo a Materiales',
            },
        ),
        migrations.CreateModel(
            name='ReglaMaterialMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiales_requeridos', models.JSONField(help_text="Lista de dicts: [{'codigo': 'MAT002', 'cantidad': 2}, ...]", verbose_name='Materiales Requeridos')),
                ('material_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_materiales_origen', to='app.material', to_field='codigo', verbose_name='Material de Origen')),
            ],
            options={
                'verbose_name': 'Regla Material a Material',
                'verbose_name_plural': 'Reglas Material a Materiales',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Tarea')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha Fin Estimada')),
                ('costo_mano_de_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Mano de Obra (Tarea)')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fase', verbose_name='Fase')),
            ],
        ),
        migrations.CreateModel(
            name='RequerimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad Requerida')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material', verbose_name='Material')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarea', verbose_name='Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad Medida')),
                ('fecha_medicion', models.DateField(verbose_name='Fecha de Medición')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material', verbose_name='Material')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarea', verbose_name='Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas Trabajadas')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personal', verbose_name='Personal')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarea', verbose_name='Tarea')),
            ],
        ),
    ]
