# Generated by Django 5.2.5 on 2025-09-23 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Material')),
                ('familia', models.CharField(max_length=100, verbose_name='Familia del Material')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Material')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo Unitario')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Alternativo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Obra')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección de la Obra')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha Fin Estimada')),
                ('presupuesto_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Presupuesto Inicial')),
                ('ingeniero_encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_ingeniero', to=settings.AUTH_USER_MODEL, verbose_name='Ingeniero Encargado')),
                ('centro_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_centro_servicio', to='app.personal', verbose_name='Centro de Servicio (Personal Técnico)')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Fase')),
                ('presupuesto_asignado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Presupuesto Asignado')),
                ('costo_mano_de_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Mano de Obra (Fase)')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.obra', verbose_name='Obra')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Tarea')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha y Hora de Inicio')),
                ('fecha_fin_estimada', models.DateField(verbose_name='Fecha Fin Estimada')),
                ('costo_mano_de_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Mano de Obra (Tarea)')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fase', verbose_name='Fase')),
            ],
        ),
        migrations.CreateModel(
            name='RequerimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad Requerida')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material', verbose_name='Material')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarea', verbose_name='Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='MedicionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad Medida')),
                ('fecha_medicion', models.DateField(verbose_name='Fecha de Medición')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material', verbose_name='Material')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarea', verbose_name='Tarea')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Horas Trabajadas')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personal', verbose_name='Personal')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarea', verbose_name='Tarea')),
            ],
        ),
    ]
