# Generated by Django 5.2.5 on 2025-08-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='costo_por_hora',
        ),
        migrations.AddField(
            model_name='fase',
            name='costo_mano_de_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Mano de Obra (Fase)'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='costo_mano_de_obra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo de Mano de Obra (Tarea)'),
        ),
    ]
