# Generated by Django 5.2.5 on 2025-09-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionMaterial',
        ),
    ]
