# Generated by Django 5.2.5 on 2025-10-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='toneladas_frio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Toneladas de Frío'),
        ),
    ]
