# Generated by Django 5.2.5 on 2025-11-26 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Cotización')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('datos_corrida_historico', models.JSONField(blank=True, null=True, verbose_name='Datos de la Corrida al momento de cotizar')),
                ('corrida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.corrida', verbose_name='Corrida Origen')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Solicitada')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (al momento de cotizar)')),
                ('costo_total_linea', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Total de Línea')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_cotizados', to='app.cotizacion')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.equipo', verbose_name='Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Total Requerida')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (al momento de cotizar)')),
                ('costo_total_linea', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Total de Línea')),
                ('origen_regla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origen (Directo, Equipo, Material)')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_cotizados', to='app.cotizacion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.material', verbose_name='Material')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaEquipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad por Equipo')),
                ('equipo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_materiales', to='app.equipo', verbose_name='Equipo de Origen')),
                ('material_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_equipos', to='app.material', verbose_name='Material Requerido')),
            ],
            options={
                'verbose_name': 'Regla Equipo a Material',
                'verbose_name_plural': 'Reglas Equipo a Materiales',
                'unique_together': {('equipo_origen', 'material_requerido')},
            },
        ),
        migrations.CreateModel(
            name='ReglaMaterialMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad por Material de Origen')),
                ('material_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_materiales_origen', to='app.material', verbose_name='Material de Origen')),
                ('material_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_materiales_requerido', to='app.material', verbose_name='Material Requerido')),
            ],
            options={
                'verbose_name': 'Regla Material a Material',
                'verbose_name_plural': 'Reglas Material a Materiales',
                'unique_together': {('material_origen', 'material_requerido')},
            },
        ),
    ]
