# Generated by Django 5.2.5 on 2026-01-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrida',
            old_name='correlaivo',
            new_name='correlativo',
        ),
    ]
