# Generated by Django 5.2.5 on 2026-01-19 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='corrida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corrida', verbose_name='Corrida Origen'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre de la Cotización'),
        ),
    ]
