# Generated by Django 5.2.5 on 2025-10-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_obra_toneladas_frio'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Disponible'),
        ),
    ]
