# Generated by Django 5.2.5 on 2025-08-24 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_personal_costo_por_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad Medida')),
                ('fecha_medicion', models.DateField(verbose_name='Fecha de Medición')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material', verbose_name='Material')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarea', verbose_name='Tarea')),
            ],
        ),
    ]
