# Generated by Django 5.2.5 on 2025-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cotizacion_cotizacionequipo_cotizacionmaterial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacionmaterial',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacionmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='costo_total',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='datos_corrida_historico',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='datos',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CotizacionEquipo',
        ),
        migrations.DeleteModel(
            name='CotizacionMaterial',
        ),
    ]
