# Generated by Django 5.2.5 on 2025-08-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicionmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
