# Generated by Django 5.2.5 on 2025-11-11 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_material_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='especialidad',
            field=models.CharField(choices=[('Instalación VRF', 'Instalación VRF'), ('Instalación CHW', 'Instalación CHW'), ('Mantenimiento', 'Mantenimiento'), ('Ductería P3', 'Ductería P3'), ('Ductería Galvanizada', 'Ductería Galvanizada'), ('Obra Civil', 'Obra Civil'), ('Eléctricidad', 'Electricidad'), ('Izaje', 'Izaje')], default=django.utils.timezone.now, max_length=50, verbose_name='Especialidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='rif',
            field=models.CharField(default='J-0001', max_length=20, unique=True, verbose_name='RIF'),
            preserve_default=False,
        ),
    ]
