# Generated by Django 5.2.5 on 2025-11-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_personal_especialidad_personal_rif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Equipo')),
                ('modelo', models.CharField(max_length=50, unique=True, verbose_name='Código del Equipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Equipo')),
                ('sistema', models.CharField(choices=[('VRF', 'VRF'), ('Chiller', 'Agua Helada (Chilled Water)'), ('fancoil', 'Fan Coil'), ('UMA', 'Unidad Manejadora de Aire')], default='VRF', max_length=10, verbose_name='Tipo de Sistema')),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capacidad del Equipo')),
                ('mca', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='mca')),
                ('mcc', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='mcc')),
            ],
        ),
    ]
