# Generated by Django 5.2.5 on 2026-01-26 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(max_length=50)),
                ('equipo', models.CharField(max_length=50)),
                ('reporte', models.CharField(max_length=75)),
                ('falla', models.CharField(max_length=50)),
                ('coordinador', models.CharField(max_length=50)),
                ('estatus', models.BooleanField(default=False)),
                ('urgencia', models.CharField(max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('personal', models.CharField(blank=True, max_length=50, null=True)),
                ('encargado', models.CharField(blank=True, max_length=50, null=True)),
                ('refrigerante', models.CharField(blank=True, max_length=50, null=True)),
                ('kilos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gasto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ods_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
