# Generated by Django 5.2.5 on 2026-01-27 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.equipo'),
        ),
    ]
