# Generated by Django 5.2.5 on 2026-01-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_reporte_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='falla',
            field=models.CharField(choices=[('No Enciende', 'No Enciende'), ('No Enfría', 'No Enfría'), ('Hace Ruido', 'Hace Ruido'), ('Fuga de Gas', 'Fuga de Gas'), ('No Arranca Compresor', 'No Arranca Compresor'), ('Error Electrónico', 'Error Electrónico'), ('Mantenimiento', 'Mantenimiento'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
