# Generated by Django 5.2.5 on 2026-01-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_delete_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='coordinador',
        ),
    ]
