# Generated by Django 5.2.5 on 2026-02-01 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_reporte_falla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estatus',
            field=models.CharField(choices=[('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='falla',
            field=models.CharField(choices=[('Mecánica', 'Mecánica'), ('Electrica', 'Electrica'), ('Control', 'Control'), ('Falso Reporte', 'Falso Reporte'), ('Preventivo', 'Preventivo'), ('Mantenimiento', 'Mantenimiento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='personal',
            field=models.CharField(blank=True, choices=[('Cuadrilla CBT', 'Cuadrilla CBT'), ('Centro de Servicio', 'Centro de Servicio')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='refrigerante',
            field=models.CharField(blank=True, choices=[('R-22', 'R-22'), ('R-134a', 'R-134a'), ('R-290', 'R-290'), ('R-404A', 'R-404A'), ('R-407C', 'R-407C'), ('R-410A', 'R-410A'), ('R-422D', 'R-422D'), ('R-507', 'R-507'), ('R-717 (NH3)', 'R-717 (NH3)'), ('R-718 (H2O)', 'R-718 (H2O)'), ('R-744 (CO2)', 'R-744 (CO2)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='urgencia',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='servicio.cliente'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='servicio.cliente')),
            ],
        ),
    ]
